### ISSUE TITLE
Validate gene symbols

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/pathway-mapper#12]
We should implement an operation (Edit > Validate Gene Symbols) that somehow checks (BioGene?) whether or not each of the gene symbols is valid and highlights any that is not!

**Comment by cannin** [comment]
This came up on a call today as being important because an analysis missed results due to mapping issues. One of the CBioPortal people showed me the API they have, but also mentioned it is not completely stable. Niki will likely have more information on this. The alternative is to get symbols directly from HGNC: 

http://www.genenames.org/cgi-bin/statistics

They provide a JSON download.

**Comment by ugurdogrusoz** [comment]
This could go as View > Check Gene Symbols. As a result, genes with invalid symbols would be highlighted (using cytoscape.js-view-utilities extension) with a message on the lower right corner that says either one of the following:
- All gene symbols are valid
- Highlighted genes have invalid symbols

**Comment by cannin** [comment]
This should be a good feature. There is some R code for the way I thought about the CBioPortal gene name validation. 

https://bitbucket.org/cbio_mskcc/pancanatlas/src/master/checkGeneNames.R

**Comment by istemi-bahceci** [comment]
The beta API at cBioPortal seems promising:

 'http://www.cbioportal.org/beta/api/genes/TP53'

It seems we can validate genes with the above API call  in pathway mapper easily.

**Comment by ugurdogrusoz** [comment]
Done with https://github.com/iVis-at-Bilkent/pathway-mapper/commit/b1636bc9a0ec0bda8d333cbf3585531e9c86cceb
