### ISSUE TITLE
Edge label orientation

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/pathway-mapper#240]
Interactions in PathwayMapper can hold labels. Let's try changing their orientation to [autorotate](https://js.cytoscape.org/demos/labels/) though. We want to make sure they are readable though due to the intersection of the edge line and label overlap. Maybe an offset could be used?

**Comment by msalihaltun** [comment]
I put a small margin on y-axis so that the edge and the label won't overlap when edge is horizontally aligned, but it still overlaps when it is vertically aligned (can just rotate the connected nodes around to see the effect). I also tried adding a margin on x-axis as well as the y-axis, but in that case the overlap still occurs when the edge is angled. So it seems to me that there will always be two opposite edge angles where the label and the edge line will overlap.

**Comment by ugurdogrusoz** [comment]
I wonder if we can adjust the margin dynamically depending on whether or not the edge is horizontal or vertical if not too expensive.

**Comment by msalihaltun** [comment]
I'm not sure how we would implement that, sounds complicated unless there is a way to do it in the cytoscape core, I couldn't find it though.

**Comment by ugurdogrusoz** [comment]
@hasanbalci spotted this: https://github.com/cytoscape/cytoscape.js/issues/2329. Let's see if it works for us.

**Comment by msalihaltun** [comment]
It works well. Thanks @hasanbalci.

**Comment by ugurdogrusoz** [comment]
How about decreasing empty space, bringing the label closer to the edge?
Also SVG export is missing edge labels.

**Comment by msalihaltun** [comment]
Turns out we never implemented text labels for edges on SVG export. Maybe we should work on this under this related issue: https://github.com/iVis-at-Bilkent/pathway-mapper/issues/232.

**Comment by ugurdogrusoz** [comment]
Sounds good. Please add this to #232. And bring labels closer to edges for the remaining task of this issue.

**Comment by msalihaltun** [comment]
Forgot to link to this issue in commit message but the task is done: https://github.com/iVis-at-Bilkent/pathway-mapper/commit/45c42b27f69671a4209e1b429ca9fd233fd0e899.
