### ISSUE TITLE
Gene search

### ISSUE THREAD

**Issue by istemi-bahceci** [iVis-at-Bilkent/pathway-mapper#68]
Let the user search for gene(s) with certain text in their labels and highlight them

**Comment by ugurdogrusoz** [comment]
How do I test this and any other fixes, improvements?

**Comment by istemi-bahceci** [comment]
I've updated deployment on http://www.pathwaymapper.org:3000/

**Comment by ugurdogrusoz** [comment]
Let's expose this with 1.1.3 milestone/release. So we should merge this functionality to the main branch. 

Also modify the Highlight menu as follows:
- Highlight Invalid Genes -> Identify Invalid Genes
- Search Genes by Name... (new menu item that moves focus to the search field on the sidebar; search highlights genes that contain provided text)
- Remove Highlights

Need to make sure highlighting is consistent! Let's discuss

**Comment by leonarddrv** [comment]
@istemi-bahceci Please make sure to fix the undo part of Remove highlight regarding Invalid Genes

**Comment by ugurdogrusoz** [comment]
When a node is highlighted due to search, we cannot see whether or not the node is selected! Since we're using the same attribute (background color) to signify both selection and highlight, there is a clash. How about just making the border "thicker" when a node is highlighted due to search? That doesn't clash with selection or invalid gene highlight (border color).

**Comment by istemi-bahceci** [comment]
@leonarddrv  we decided to remove undo and redo functionality of invalid gene highlight thing. Can you look at this ?

**Comment by ugurdogrusoz** [comment]
Let's reconsider having this undoable
